### ISSUE TITLE
Add more info on landing page

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/bristlemouth-explorer#18]
The landing page is a bit hard to grasp without context. We should add an info text to briefly explain what Bristlemouth is and what this project is about.

**Comment by Caesarh97** [comment]
Just adding some brainstorming ideas. We could maybe include a text that describes what the BE does. We could also add something at the bottom that links to the pioneer program: https://www.bristlemouth.org/pioneer.
![image](https://github.com/aqualinkorg/bristlemouth-explorer/assets/113801743/b90d3739-c545-417f-8db7-87131b8bb4b6)

**Comment by ericboucher** [comment]
Fixed in #19
